# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: GitHub Commit & Push
      uses: actions-js/push@v1.3 # marketplace search -> "actions-js push"
      with:
        github_token: ${{secrets.GIT_AUTH_SECRET}}
        author_email: commit&push@github.actions
        author_name: github.actions.commit&push
        message: build commit
